services:
  db:
    image: postgres:18.3
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: exam_user
      POSTGRES_PASSWORD: exam_password
      POSTGRES_DB: exam_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exam_user -d exam_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "1910:1910"
    environment:
      EXAMARCHIVE_DEV_MODE: "true"
      EXAMARCHIVE_DB_HOSTNAME: "db"
      EXAMARCHIVE_DB_PORT: "5432"
      EXAMARCHIVE_DB_USERNAME: "exam_user"
      EXAMARCHIVE_DB_PASSWORD: "exam_password"
      EXAMARCHIVE_DB_DATABASE: "exam_db"
      KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REDIRECT_URI: "http://localhost:1910/auth/callback"
      KEYCLOAK_USER_AFFILIATION: "student@uni-muenster.de"
      KEYCLOAK_ADMIN_AFFILIATION: "3809c3c5-058e-4d4d-ade7-5466d18e819d"

volumes:
  postgres_data: